export const hiringData = [
  {
    month: "January",
    company: "Uber",
    logo: "uber",
    program: "UberHack",
    window: "January",
    target: "3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "January",
    company: "Uber",
    logo: "uber",
    program: "C++ Program",
    window: "January",
    target: "2nd Year Female Candidates",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "January",
    company: "American Express",
    logo: "americanexpress",
    program: "CodeStreet",
    window: "January",
    target: "1st, 2nd, 3rd, or 4th Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "January",
    company: "RBI",
    logo: "rbi",
    program: "RBI Research Internship",
    window: "January",
    target: "1st, 2nd, 3rd, or 4th Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "February",
    company: "Google",
    logo: "gsoc",
    program: "Google Summer of Code (GSoC)",
    window: "February – March (Proposal Submission)",
    target: "All College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "February",
    company: "J.P. Morgan",
    logo: "jpmorgan",
    program: "Code For Good",
    window: "February",
    target: "2nd and 3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "February",
    company: "Walmart",
    logo: "walmart",
    program: "CodeHers",
    window: "February",
    target: "3rd Year Female Candidates",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "February",
    company: "ServiceNow",
    logo: "servicenow",
    program: "Women Code To Win",
    window: "February",
    target: "Female Candidates (All Years)",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "March",
    company: "Juspay",
    logo: "juspay",
    program: "Hiring Challenge",
    window: "March",
    target: "3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "March",
    company: "GitHub",
    logo: "github",
    program: "GitHub Externship",
    window: "March",
    target: "3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "March",
    company: "Flipkart",
    logo: "flipkart",
    program: "Flipkart Runway Program",
    window: "March",
    target: "2nd and 3rd Year Female Candidates",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "April",
    company: "Myntra",
    logo: "myntra",
    program: "HackerRamp",
    window: "April",
    target: "2nd and 3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "April",
    company: "LinkedIn",
    logo: "linkedin",
    program: "Coaching Program",
    window: "April",
    target: "2nd and 3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "May",
    company: "Microsoft",
    logo: "microsoft",
    program: "Microsoft Engage Program",
    window: "May",
    target: "2nd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "May",
    company: "Cisco",
    logo: "cisco",
    program: "Ideathon",
    window: "May",
    target: "2nd and 3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "June",
    company: "Goldman Sachs",
    logo: "goldmansachs",
    program: "Summer Analyst Program",
    window: "June",
    target: "3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "June",
    company: "Swiggy",
    logo: "swiggy",
    program: "Swiggy Launchpad",
    window: "June",
    target: "All College Students (1st, 2nd, 3rd, or 4th Year)",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "July",
    company: "Flipkart",
    logo: "flipkart",
    program: "Flipkart Grid Program",
    window: "July",
    target: "2nd and 3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "July",
    company: "Meta/Facebook",
    logo: "meta",
    program: "Hacker Cup",
    window: "July",
    target: "All College Students (1st, 2nd, 3rd, or 4th Year)",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "July",
    company: "Juspay",
    logo: "juspay",
    program: "Hiring Challenge",
    window: "July",
    target: "3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "August",
    company: "CodeNation",
    logo: "codenation",
    program: "CodeAGON",
    window: "August",
    target: "2nd and 3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "August",
    company: "D. E. Shaw",
    logo: "deshaw",
    program: "Ascent (Diversity Hiring)",
    window: "August",
    target: "2nd and 3rd Year Female Candidates",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "September",
    company: "Google",
    logo: "google",
    program: "SDE Intern Program",
    window: "September",
    target: "2nd and 3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "September",
    company: "Adobe",
    logo: "adobe",
    program: "SDE Intern Program",
    window: "September",
    target: "2nd and 3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "October",
    company: "Amazon",
    logo: "amazon",
    program: "SDE Internship",
    window: "October",
    target: "2nd and 3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "October",
    company: "EY",
    logo: "ey",
    program: "Techathon",
    window: "October",
    target: "2nd and 3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "November",
    company: "Intuit",
    logo: "intuit",
    program: "SDE Internship",
    window: "November",
    target: "3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "November",
    company: "Uber",
    logo: "uber",
    program: "UberStar",
    window: "November",
    target: "2nd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "November",
    company: "Morgan Stanley",
    logo: "morganstanley",
    program: "SDE Internship",
    window: "November",
    target: "3rd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "December",
    company: "Google",
    logo: "google",
    program: "STEP Intern Program",
    window: "December",
    target: "2nd Year College Students",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "December",
    company: "Amazon",
    logo: "amazon",
    program: "WOW Program (Women of the World)",
    window: "December",
    target: "1st, 2nd, and 3rd Year Female Candidates",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
  {
    month: "December",
    company: "American Express",
    logo: "americanexpress",
    program: "Geek Gods",
    window: "December",
    target: "3rd Year Female Candidates",
    link: "Not explicitly mentioned in video; check company careers page or platforms like Unstop/HackerEarth.",
  },
];
